### PR TITLE
grpc driver

### PR DESCRIPTION
**Pull request by rachel-wine**

### CODE REVIEW

**Comment by rachel-wine** [comment]
[(3) Plugin Gatik - Ottojoy #SP.40 $](https://trello.com/c/I7mbK1IQ/1857-3-plugin-gatik-ottojoy-sp40)

**Comment by idorottopia** [comment]
Is it a draft?
if so, please convert this PR to one :)

**Comment by idorottopia** [comment]
2483 files changed.
Good luck @AlexK-Otto

**Comment by idorottopia** [comment]
2483 files changed.

Good luck @AlexK-Otto !

**Pull request closed without merging**
